name: Parking Data Scraper

on:
  schedule:
    - cron: '*/15 * * * *' 
  workflow_dispatch:      

permissions:
  contents: write         

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the Scraper
        run: python GetApicall.py  

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add parking_data.csv
          git commit -m "Auto-update parking data" || exit 0
          git push
